'use client';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from 'styled-components';
import { GlobalStyles } from './global.styled';
import theme from './theme';
import ReduxProvider from '@/redux/ReduxProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'OmniAI | Your all-in-one AI tools platform',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider theme={theme}>
      <ReduxProvider>
        <GlobalStyles />
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </ReduxProvider>
    </ThemeProvider>
  );
}
