import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import theme from './theme';
import ReduxProvider from '@/redux/ReduxProvider';
import StyledComponentsRegistry from '@/lib/decorators/registry';
import StyledComponentsThemeProvider from '@/lib/decorators/StyledComponentsThemeProvider';
import ToastProvider from '@/lib/decorators/ToastProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'OmniAI | Your all-in-one AI tools platform',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StyledComponentsThemeProvider>
      <ReduxProvider>
        <html lang="en">
          <body className={inter.className}>
            <ToastProvider>
              <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
            </ToastProvider>
          </body>
        </html>
      </ReduxProvider>
    </StyledComponentsThemeProvider>
  );
}
